### ISSUE TITLE
Title and Author text almost overlap.

### ISSUE THREAD

**Issue by pbstudent** [BCcampus/pressbooks-textbook#103]
PBT v. 3.1.0

Text is very tight in Windows/Mac CHROME, and Mac Safari.  Windows/Mac Firefox displays the best.
Results:
MAC CHROME
![chrome](https://user-images.githubusercontent.com/24277755/28733203-45ed89f6-73db-11e7-88b3-9013c730b3ee.png)

MAC SAFARI
![safari](https://user-images.githubusercontent.com/24277755/28733220-53b6743a-73db-11e7-9a47-396b61b35a58.png)

MAC FIREFOX
![firefox](https://user-images.githubusercontent.com/24277755/28733226-5d037ca4-73db-11e7-8610-3e3b057a1aa5.png)

Windows 7 IE11
![w7-ie11](https://user-images.githubusercontent.com/24277755/28733241-7041e440-73db-11e7-9ded-2dab31946184.PNG)

**Comment by bdolor** [comment]
Yikes! Thanks for reporting this. Looking into this now.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-textbook/commit/e22e44c641a3ffdf1994803f54356a208650797f released in  v3.1.1
