### ISSUE TITLE
PBT 3.1.1 update did not appear to fix chapter author & subtitle placement

### ISSUE THREAD

**Issue by JackDougherty** [BCcampus/pressbooks-textbook#104]
Thanks for the quick response to my problem report, but unless I'm misunderstanding something, I don't think that the 3.1.1 update fixed the chapter author and subtitle placement problem. My goal is to display items in this order: title, subtitle, authors.

Here's the original 3.1.0 screenshot I sent you:
![pressbooks-textbook-3_1_0](https://user-images.githubusercontent.com/649719/28995324-7f6253d6-79b4-11e7-980f-e408384912d2.png)

And here's the same page after I updated to 3.1.1, which does not appear to have changed:
<img width="1347" alt="pbt-3_1_1-chapter_authors_and_subtitle" src="https://user-images.githubusercontent.com/649719/28995331-9eee0e66-79b4-11e7-8aaa-44a800e5dcf8.png">

I tried de-activating and reactivating the new version, and temporarily switching themes to Luther and back to PBT, and viewing on different browsers, but nothing worked. FYI, the Theme is still Open Textbooks v1.0

Here's the live page link. Let me know if you need more info from me, or if I'm doing something wrong.
https://epress.trincoll.edu/webwriting/chapter/hagood-price/

**Comment by bdolor** [comment]
This is what the live page looks like for me: 

![image](https://user-images.githubusercontent.com/2048170/28996190-f1d6cafa-79af-11e7-8115-4a95babe3263.png)

**Comment by JackDougherty** [comment]
You are correct! I have no idea why neither of my browsers displayed this correctly a few hours ago, even when I did a hard refresh of the cache. Just when I thought I kinda knew what I was doing...

Thanks for all of your work on PB and PBTB
