### ISSUE TITLE
Automate organization of chapter content parts

### ISSUE THREAD

**Issue by alex-418** [BCcampus/pressbooks-textbook#112]
Chapters currently need to be saved and/or created after the import, and the chapter content parts have to be assigned to them manually. Instead, the chapter content should go straight into it's designated chapter after import, to save the user time.

**Comment by bdolor** [comment]
parts of this issue have been addressed in https://github.com/BCcampus/pressbooks-textbook/releases/tag/4.0.4 — will leave this issue open to resume testing at a later date.

**Comment by bdolor** [comment]
complete.
