### ISSUE TITLE
Creative Commons Configurator deprecated

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-textbook#122]
### Description 

ref: https://wordpress.org/plugins/creative-commons-configurator-1/

The plugin has been deprecated and is no longer being maintained. It is currently bundled with Pressbooks Textbook but I'm not convinced it's being used by many. A graceful degradation should be implemented in PBT.

**Comment by mxbees** [comment]
Also, I just tried to install this on our pressbooks install at York and it started giving me 500 errors until I deactivated and uninstalled. Currently trying to figure out why our various derivatives aren't showing on the front page and this looked like a solution... so it should definitely be removed.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-textbook/pull/140
