### ISSUE TITLE
Numbered lists not indented

### ISSUE THREAD

**Issue by pbstudent** [BCcampus/pressbooks-textbook#128]
### Description 
Number lists wrap to end rather indented second line.
![numberedlist](https://user-images.githubusercontent.com/24277755/30363370-25c04610-9860-11e7-8e30-456b4310a4f8.png)

**Expected behaviour** 

List indented same as bullet lists.

**Actual behaviour** 

Text wraps end to end of paragraph.

### Steps to reproduce the problem
```<ol>
 	<li>Pressbooks SVG
<ol>
 	<li>invoke the SVG Support plugin and modifying the Pressbook Settings &gt; Network Settings &gt; Upload file types &gt; SVG.</li>
 	<li>Create a duplicate content of the chapters with long tables and substitute the long HTML tables with the corresponding SVG file from below.</li>
</ol>
</li>
 	<li>Authoring SVG Tables (assuming SVG Support plugin installed) - Install LibreOffice[footnote]https://en.wikipedia.org/wiki/LibreOffice[/footnote] 5.x and create a new Spreadsheet.  Select relevant cells, copy then create a new Drawing and Paste Special, and then select calc# from list.  Select relevant objects and export to SVG (enable Automatic file name extension and Selection).  Add SVG file into Pressbooks.</li>
</ol>
```

### System Information

- Pressbooks Textbook: 3.1.1
- Pressbooks: 4.3.0
- WordPress: 4.8.1
- Root Theme: Pressbooks Publisher 2.1

**Comment by bdolor** [comment]
Hi @pbstudent — this has been addressed in the dev branch via https://github.com/BCcampus/pressbooks-textbook/commit/77712d706e9de5dea2e9fdf0bb1b139d55421a35 I will be drafting a new release soon where you should see the change. Thanks!

**Comment by pbstudent** [comment]
Thanks,
Will that change also take care of level 2 in a list?

Regards,
Steve
