### ISSUE TITLE
Wordpress.org still showing PBT 3.1.5

### ISSUE THREAD

**Issue by pbstudent** [BCcampus/pressbooks-textbook#132]
- Pressbooks Textbook: 3.1.6 available yet in Wordpress.org? as version number for 3.1.6 is still showing 3.1.5 in WP plugin list when installed via FTP manual on test site.

Thanks,

**Comment by bdolor** [comment]
seems strange then that the wp svn repo was updated three days ago, yet the change isn't showing on wp.org https://plugins.trac.wordpress.org/changeset/1756162 

![image](https://user-images.githubusercontent.com/2048170/32382939-e0176ad0-c073-11e7-8324-531177e61850.png)

**Comment by pbstudent** [comment]
v.3.1.6 folder extract reveals pressbooks-textbook.php with "3.1.5"

So not sure if that is related

**Comment by bdolor** [comment]
thank you — my mistake. I've updated the version number in that file http://plugins.trac.wordpress.org/changeset/1758129 

I'm assuming WP org has a caching mechanism...still not seeing it reflect on wp.org

**Comment by pbstudent** [comment]
Hopefully soon as I really need this update.

Thanks,
Cheers,
Steve

**Comment by bdolor** [comment]
it is displaying the correct version now: https://wordpress.org/plugins/pressbooks-textbook/

**Comment by pbstudent** [comment]
updated successfully!
thanks
