### ISSUE TITLE
Text Alignment displayed differently in Safari

### ISSUE THREAD

**Issue by pbstudent** [BCcampus/pressbooks-textbook#136]
### Description 

Author info displayed ok in Mac Firefox but mis-aligned in Safari.

**Expected behaviour** 

Field names aligned with description info.

**Actual behaviour** 

Mis-alignment of text.

### Steps to reproduce the problem

1. Author info:
![edit book information creative clinical teaching in the health professions pressbooks](https://user-images.githubusercontent.com/24277755/32702395-dde2e76a-c7e6-11e7-976e-8ca573ae0b78.png)
2. Safari Display:
![mac-safari](https://user-images.githubusercontent.com/24277755/32702401-ef0c14ee-c7e6-11e7-83ed-5e9a165ef061.png)
3. Firefox Displayed relatively better:
![firefox](https://user-images.githubusercontent.com/24277755/32702406-fae66530-c7e6-11e7-9246-62f42c53f2b0.png)

### System Information

- Pressbooks Textbook: [3.1.6] 
- Pressbooks: [4.3.5] 
- WordPress: [4.8.3]

**Comment by bdolor** [comment]
The parent theme McLuhan has brought in some bold changes including the footer where this ticket would have been focused.
