### ISSUE TITLE
Replace `pb_author`, `pb_contributing_authors` and `pb_section_author` with new slugs

### ISSUE THREAD

**Issue by connerbw** [BCcampus/pressbooks-textbook#139]
### Description 

Pressbooks 5 introduces modular contributors, 

More info:
https://pressbooks.org/blog/2018/01/17/pressbooks-5-developer-guide/

For backwards-compatibility, the new contributor field names are pluralized and any 3rd party code that looks for the old fields will still be able to retrieve them. If a plugin saves using the old slugs we catch these and convert to the new format. [1] Making absolutely no changes to your code may surprisingly work for a long time. 

_Importing, cloning, moving to/from external systems, and things we can't predict will eventually lead to the old slugs going stale though._

My request is that when PB5 is released, please replace `pb_author`, `pb_contributing_authors` and `pb_section_author` with new slugs Developers can find several convenience methods in the `\Pressbooks\Contributors` [2] class. 

Examples:

```php
$contributors->isValid($contributor_type);
$contributors->isDeprecated($contributor_type);
$contributors->maybeUpgradeSlug($old_slug);
$contributors->convert( $old_slug, $names, $post_id );
```

If you need peer review we can do our best to have a look when there's something to look at?

Thanks.

 1. https://github.com/pressbooks/pressbooks/blob/3fe31d85b46b46b6da8df7229716e50f55b6f776/inc/class-taxonomy.php#L573
 2.  https://github.com/pressbooks/pressbooks/blob/dev/inc/class-contributors.php

### System Information

 + https://github.com/search?q=org%3ABCcampus+pb_author&type=Code
 + https://github.com/search?utf8=%E2%9C%93&q=org%3ABCcampus+pb_section_author&type=Code
 + https://github.com/search?q=org%3ABCcampus+pb_contributing_authors&type=Code&utf8=%E2%9C%93

- Pressbooks: 5.0.0 (or dev branch)
- WordPress: 4.9.2

**Comment by bdolor** [comment]
thank you!

**Comment by bdolor** [comment]
References to `pb_author`, `pb_contributing_authors` and `pb_section_author` have been replaced.
