### ISSUE TITLE
CSS issues with Pressbooks Textbook

### ISSUE THREAD

**Issue by SteelWagstaff** [BCcampus/pressbooks-textbook#141]
### Description 

Hi Brad--we've noticed a couple of CSS issues with the new Pressbooks Textbook theme. First, there's a small issue with the margin/padding of the ordered list items in the new table of contents.

**Expected behaviour** 

We want the ordered list to look the way it does in McLuhan:
<img width="388" alt="screen shot 2018-03-05 at 9 36 48 am" src="https://user-images.githubusercontent.com/13485451/36983771-d7a66f0a-2058-11e8-93ef-c6f979a2c207.png">

**Actual behaviour** 

Instead, the list looks a bit janky: 
<img width="371" alt="screen shot 2018-03-05 at 9 38 18 am" src="https://user-images.githubusercontent.com/13485451/36983824-fb6b7e12-2058-11e8-8f47-72fbd1804a7e.png">

It appears to me that the Pressbooks Textbook theme is inserting a counter in the before pseudo-element for each of these list items, and that there isn't enough margin-left space to display it. Changing the margin-left value to 1.3rem would fix it, though we'd then have duplicate numbers there. Perhaps it might be better to remove the before counter increment from the theme entirely? If you do want to keep it, you may also want to change the behavior of the .toc__front-matter div.inner-content elements. Those divs are currently displaying as block elements, and you may want them to display inline so that they're on the same line as the ::before letters/numbers.

**Comment by SteelWagstaff** [comment]
Thanks Ned--I've switched themes a few times (to McLuhan, to Austen, and to a few others) and back, and cleared my browser cache, but am still seeing the issue persist.

**Comment by greatislander** [comment]
Darn, okay.

**Comment by bdolor** [comment]
Thank you for reporting @SteelWagstaff — I'll look into this.

**Comment by bdolor** [comment]
@lucwrite - should be taken care of via https://github.com/BCcampus/pressbooks-textbook/pull/149 can you please confirm?

**Comment by bdolor** [comment]
@SteelWagstaff - thank you very much for reporting this. Should be resolved with https://github.com/BCcampus/pressbooks-textbook/releases/tag/4.0.1
