### ISSUE TITLE
Declare compatibility with Pressbooks

### ISSUE THREAD

**Issue by connerbw** [BCcampus/pressbooks-textbook#142]
### Description 

Please add: `Pressbooks tested up to: 5.0.2`

Or similar to your plugin? More info:

 + https://pressbooks.org/blog/2018/03/05/declaring-your-plugins-compatibility-with-pressbooks/

Thanks!

**Comment by bdolor** [comment]
thanks @connerbw - addressed in https://github.com/BCcampus/pressbooks-textbook/pull/149/commits/ab1a3481e72b02a70290919f123cf645797b5b65 and will be applied to other plugins for pb.
