### ISSUE TITLE
paragraph indents

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-textbook#144]
### Description 

Every paragraph is indented including the Fig even though Indent in Web options is not selected

**Expected behaviour** 

not to do that

**Actual behaviour** 

all the paragraphs indented

### Steps to reproduce the problem

https://opentextbcdev.bccampus.ca/teachinginadigitalage/chapter/structural-changes-in-the-economy-the-growth-of-a-knowledge-society/

**Comment by bdolor** [comment]
@lucwrite - should also be taken care of with https://github.com/BCcampus/pressbooks-textbook/pull/149 please confirm.

**Comment by lucwrite** [comment]
Can I  move the remainder of these items into Done as I confirm?

**Comment by bdolor** [comment]
yes please
