### ISSUE TITLE
Narrow or Widen web-view theme option not working 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/pressbooks-textbook#145]
### Description 

A designer or instructor should be able to narrow or widen the web view of a text. (This currently works with Mculan)

**Expected behavior** 

Web view of book can be made narrow, wide or standard using Web theme options

**Actual behaviour** 

Web view of book does not change when Theme options setting is change. 

### Steps to reproduce the problem

Change or set the theme options and visit the web view

**Comment by lucwrite** [comment]
Confirmed that now books in Open Textbook can be set Narrow, Wide or Standard

**Comment by alex-418** [comment]
@lucwrite great, I was just going to write the same thing, can confirm it worked for me as well.

**Comment by bdolor** [comment]
@alex-418 - but to be clear, nothing was changed?

**Comment by alex-418** [comment]
@bdolor That is correct. @lucwrite Nothing was changed, any other info you could provide so we could replicate this issue? For now, it seems that it has been working as expected

**Comment by lucwrite** [comment]
I can confirm that this function was not working until today. Tested multiple times.
