### ISSUE TITLE
Network config 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-textbook#146]
### Description 

Control of catalogue filters by topic on network site (aldine)

**Expected behaviour** 

would like to control catalogue filters by topic 

**Actual behaviour** 

don't know where the control is

### Steps to reproduce the problem

https://opentextbcdev.bccampus.ca/l
![image](https://user-images.githubusercontent.com/2048170/37296407-1fdc1534-25d8-11e8-860a-7ea73554cffa.png)

**Comment by bdolor** [comment]
@lucwrite - The catalog area on the network page is controlled in 'Book Info' under 'Subjects': 

![image](https://user-images.githubusercontent.com/2048170/37300417-2c73838a-25e3-11e8-84cd-244359d588d3.png)

more information on this type of classification system is here: http://www.editeur.org/files/Thema/20160601%20Thema%20v1.2%20Basic%20instructions.pdf

**Comment by lucwrite** [comment]
I have tested this with other books and it works. This is not an development issue rather a function miss on my part. Can I move to the done column?

**Comment by bdolor** [comment]
please
