### ISSUE TITLE
missing TOC in PDF export

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-textbook#148]
### Description 

PDF Exports in newly created books not showing a ToC

**Expected behaviour** 

TOC should show up. 

**Actual behaviour** 

They don't 

### Steps to reproduce the problem

create a new book, export to PDF. Not sure at this point if it's theme specific.

**Comment by lucwrite** [comment]
Reproducible in in McLuhan, OpenTexbook theme and Jacobs. Cannot reproduce in Luther/Austin themes as currently these themes have export failure "There was a problem with SASS. Contact your site administrator. Error: parse error: failed at `size: ; } ` (stdin) on line 1061"

**Comment by bdolor** [comment]
@lucwrite - can you confirm if that you have display Table of Contents checked in Theme Options->PDF

![image](https://user-images.githubusercontent.com/2048170/37311430-6fc3de70-2604-11e8-883c-4c64bd1576a6.png)

**Comment by lucwrite** [comment]
Yes I can confirm this.

**Comment by bdolor** [comment]
Can you please tell me if the Table of Contents shows up if you 'Save' the PDF options? I could recreate this issue if I created a new book and exported right away. But if I saved the PDF options in Appearance->Theme Options (and did nothing else) the TOC would show up in the export. If you can recreate this it may be something you'd want to report to PB.
