### ISSUE TITLE
Unable to import an .html file with the "Web page/Pressbooks webbook (.html or URL)" import option

### ISSUE THREAD

**Issue by josieg** [BCcampus/pressbooks-textbook#150]
### Description 

On the import page in Pressbooks, the "Web page/Pressbooks webbook (.html or URL)" import option allows users to either upload a file or import from a URL. The URL import works as expected, but trying to import an .html file does not work. 

**Expected behaviour** 

With the "Web page/Pressbooks webbook (.html or URL)" import option, there is an option to upload a file or import via a link. With both of those options present, I assume that I am able to import an .html file. 

If the "Web page/Pressbooks webbook (.html or URL)" import option is not designed to import an .html file, the option to upload a file should be removed for this import option. 

**Actual behaviour** 

1. I select the "Web page/Pressbooks webbook (.html or URL)" import option in Pressbooks.
2. I upload an .html file from a book in Pressbooks. 
3. I import the file. It is successful.
4. I go to the "Organize" page to view the imported content. It looks like the entire book has been added to one chapter. And when I click on the chapter, there is no content.

### System Information

- Textbooks for Pressbooks: [4.0.1] 
- Pressbooks: [5.0.2] 
- WordPress: [4.9.4]

**Comment by bdolor** [comment]
I would think the html file being brought in as one chapter is expected behaviour, but the chapter having no content may be something you want to bring up with https://github.com/pressbooks/pressbooks or https://discourse.pressbooks.org
