### ISSUE TITLE
Table Captions PB5 

### ISSUE THREAD

**Issue by lucwrite** [BCcampus/pressbooks-textbook#152]
### Description 

Table captions added via <caption> tags in the html editor aren't displaying properly in web view.

**Expected behaviour** 

Captions added to tables appear above the table they refer to, are centred, bolded, and in black font. (This is the case in the edit view, and the exported file formats)

**Actual behaviour** 

Captions appear below tables, left justified, in a bolded, light-grey font.

### Steps to reproduce the problem
1. Add a table to a new Pressbook. 
2. Add captions to the table
3. View the table in the web view

### System Information

- Textbooks for Pressbooks: [2.0] 
- Pressbooks: [5.1.0

**Comment by bdolor** [comment]
addressed in https://github.com/BCcampus/pressbooks-textbook/commit/cb862ce78593a6ae31f872d8dd2cd08a9639dab9

can be validated at https://pressbooksdev.bccampus.ca/canadianhistorypb5/front-matter/testing-new-front-matter/

**Comment by lucwrite** [comment]
Ok perfect - Looks good
