### ISSUE TITLE
Widen and Narrow Width no longer working properly

### ISSUE THREAD

**Issue by lucwrite** [BCcampus/pressbooks-textbook#155]
### Description 

This is in reference to [](https://github.com/BCcampus/pressbooks-textbook/issues/145) Content width Theme Options --> Web Options not widening or narrowing. Behaviour began again today March 20th

**Expected behaviour** 
Webbook width will change when Narrow Width or Wide Width selected

**Actual behaviour** 

Only the Adeline width changes - not the web view width will change. The webbook width remains Standard. I have replicated this in Chrome and Safari. This only occures with the Open Text theme I am able to succesfully change webbook width with Jacobs and Mcluan.

Webbook that I tested on https://opentextbc.ca/indigenizationleadersadministrators/chapter/chapter-1/

Attached screenshots show view when set to 1) Narrow 2) Wide. Webbook remains standard
![set to wide](https://user-images.githubusercontent.com/19966949/37686943-d93a11c8-2c56-11e8-8ff4-f153f13f455f.jpg)
![set to narrow](https://user-images.githubusercontent.com/19966949/37686951-e311bda4-2c56-11e8-9332-c13e45fa037e.jpg)

### Steps to reproduce the problem

1. Dashboard -- Theme Options -->Web
2. Set to narrow or wide width
3. Click save
4. View Webbook and width remains standard
(I have changed themes and clicked save.)

### System Information

-### System Information

#### Book Info

Book ID: 228
Book URL: https://opentextbc.ca/indigenizationleadersadministrators/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Chrome
Browser Version: 65.0.3325.162
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36

#### WordPress Configuration

Network URL: http://opentextbc.ca/
Network Type: Subdirectory
Version: 4.9.4
Language: en_US
WP_ENV: Not set
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.1.0
Book Theme: Open Textbooks
Book Theme Version: 2.1.1
Root Theme: Aldine
Root Theme Version: 1.1.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Akismet Anti-Spam: 4.0.3
Better WordPress Google XML Sitemaps: 1.4.1
CC Export for Pressbooks: 0.2.1
f5 Force SSL: 1.0.0
iThemes Security: 6.9.2
Openstax Import for Pressbooks: 1.0.1
Pressbooks: 5.1.0
Pressbooks Stats: 1.4.0
Textbooks for Pressbooks: 4.0.2
User Activation Keys: 4.6
WP-Piwik: 1.0.19

#### Inactive Plugins

BuddyPress: 2.9.3
H5P: 1.10.1
mPDF for Pressbooks: 3.1.1
Relevanssi: 4.0.4
WP QuickLaTeX: 3.8.4

#### Server Configuration

PHP Version: 7.1.15
MySQL Version: 5.5.5
Webserver Info: Apache

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 512M
Upload Max Size: 100M
Post Max Size: 100M
Upload Max Filesize: 100M
Time Limit: 60
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.19.7
imagick: Not Installed
xsl: Installed

**Comment by bdolor** [comment]
thanks for reporting @lucwrite

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-textbook/commit/39397341341912e856911e4c364bc865ead30548

**Comment by lucwrite** [comment]
Sorry @bdolor why is this resolved? I am still able to replicate this issue across multiple books

**Comment by lucwrite** [comment]
I was looking on production

**Comment by lucwrite** [comment]
Confirmed on dev -!
