### ISSUE TITLE
Blockquote Styling Right Margin Spacing too Tight

### ISSUE THREAD

**Issue by lucwrite** [BCcampus/pressbooks-textbook#156]
### Description 

The CSS for the blockquote in the PDF and for the Web view - text is too close to the right margin. 

**Expected behaviour** 
Spacing between right side of the blockquote shaded block and text. 

**Actual behaviour** 
Blockquote text is tight against the right side of the shared textbox. Screenshot below

1. Create a blockquote in a  PB  with OpenText theme applied
2. View either Web version or Export to Digital OR print PDF
3. Check the blockquote

PDF

![image](https://user-images.githubusercontent.com/19966949/37927881-060d3fc0-30f0-11e8-9808-f22f2ad9c785.png)

Webbook
![image](https://user-images.githubusercontent.com/19966949/37928821-ff2faa28-30f2-11e8-9d4d-4c20ab7356f7.png)

#### Book Info

Book ID: 221
Book URL: https://opentextbc.ca/indigenizationcurriculumdevelopers/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Chrome
Browser Version: 65.0.3325.162
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36

#### WordPress Configuration

Network URL: http://opentextbc.ca/
Network Type: Subdirectory
Version: 4.9.4
Language: en_US
WP_ENV: Not set
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.1.0
Book Theme: Open Textbooks
Book Theme Version: 2.1.1
Root Theme: Aldine
Root Theme Version: 1.1.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Akismet Anti-Spam: 4.0.3
Better WordPress Google XML Sitemaps: 1.4.1
CC Export for Pressbooks: 0.2.1
f5 Force SSL: 1.0.0
iThemes Security: 6.9.2
Openstax Import for Pressbooks: 1.0.1
Pressbooks: 5.1.0
Pressbooks Stats: 1.4.0
Textbooks for Pressbooks: 4.0.2
User Activation Keys: 4.6
WP-Piwik: 1.0.19

#### Book Active Plugins

H5P: 1.10.1

#### Inactive Plugins

BuddyPress: 2.9.3
mPDF for Pressbooks: 3.1.1
Relevanssi: 4.0.4
WP QuickLaTeX: 3.8.4

#### Server Configuration

PHP Version: 7.1.15
MySQL Version: 5.5.5
Webserver Info: Apache

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 512M
Upload Max Size: 100M
Post Max Size: 100M
Upload Max Filesize: 100M
Time Limit: 60
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.19.7
imagick: Not Installed
xsl: Installed

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-textbook/commit/d7e8a8474c6433c174b9d150a0c83d8e134d17e5
