### ISSUE TITLE
PDF Export: attribution size too large

### ISSUE THREAD

**Issue by alex-418** [BCcampus/pressbooks-textbook#162]
Each attribution needs to be on a single line with no indented bullet point section with a small amount of space between attributions. Appearance should be similar to current footnote format but numbered and grouped separately from footnotes. The attributions could be set to appear either under the content or like endnotes at the end of the chapter in the PDF export.

**Comment by alex-418** [comment]
@lucwrite please attach the screenshot

**Comment by bdolor** [comment]
closing, moving to a built in solution: https://github.com/BCcampus/pressbooks/projects/2
