### ISSUE TITLE
Candela citation: Fields names

### ISSUE THREAD

**Issue by alex-418** [BCcampus/pressbooks-textbook#163]
Update the field names, look into adding the ability to let the user edit them in the plugin options page. 

1.) "Description" would be better titled "Title/Description"

2.) "Author" would be better titled "Author/Copyright holder"
the "URL" box would be better titled "Link to original source"

3.) "License terms" box would be better titled "More information," and then it could be used for anything extra

4.) Second URL - There needs to be a place to put a second url in case the photographer has a flikr page or something like that, it could be called "Link to author's page"

5.) The tab where you see the attributions in the live book should be titled "Attributions," not "Citations"

As per https://jira.bccampus.ca/browse/WD-411

**Comment by bdolor** [comment]
closing, moving to a built in solution: https://github.com/BCcampus/pressbooks/projects/2
