### ISSUE TITLE
Candela citation: Attributions sorted alphabetically

### ISSUE THREAD

**Issue by alex-418** [BCcampus/pressbooks-textbook#165]
By figure number than by license type. As such, the "Type" option could be replaced by a textbox, where the person could write the number associated with the image/table, etc(Example: Figure 4.3 or Table 1.2). That would be used to sort the attributions

**Comment by bdolor** [comment]
moving to building an attribution feature in PB ref: https://github.com/BCcampus/pressbooks/projects/2
