### ISSUE TITLE
Large error message in Pressbooksdev.bccampus.ca and opentextbcdev.bccampus.ca

### ISSUE THREAD

**Issue by josiegray** [BCcampus/pressbooks-textbook#170]
### Description 

When I log into either of the dev instances of Pressbooks, a large error message pops up:
"There was a problem with SASS. Contact your site administrator. Error: Undefined variable $page-width: line: 102."

See attachment for full message

I've seen the notice on the My Catologue page and on a book's dashboard page, but sometimes it temporarily disappears. 

<img width="1067" alt="5 4 error message" src="https://user-images.githubusercontent.com/37554861/42332901-187b6974-802e-11e8-9c9e-c7de9da3dc0f.PNG">

### Steps to reproduce the problem

1. Log into one of the dev instances. Select "My Books." 
2. See error message above the Catalogue.

**Comment by bdolor** [comment]
thanks for reporting this @josieg - likely has something to do with the recently upgraded parent theme.
