### ISSUE TITLE
Text does not wrap around sidebar textboxes in the OT theme

### ISSUE THREAD

**Issue by josiegray** [BCcampus/pressbooks-textbook#172]
### Description 

When testing the new sidebar textboxes on pressbooksdev, I see that these sidebars are left-justified on the page, but text does not wrap around them. Instead, text starts underneath the sidebar textbox. I have to go into the CSS to get the text to wrap. This is a problem in the visual editor, web book, and PDFs.

Text wraps around these sidebar textboxes properly in the Jacobs and McLuhan themes. With these themes, the textboxes appear right-justified with text wrapped around them.

Here is where I am testing: https://pressbooksdev.bccampus.ca/testingadmin/chapter/chapter-1/ 
On this page, the examples sidebar has additional CSS to get the text to wrap, the exercises sidebar does not. 

**Expected behaviour** 

I add a sidebar textbox in the visual editor from the Textboxes drop-down menu. It appears left justified. The surrounding text wraps around the sidebar textbox, as it would with an image that is left or right justified. I save the book. When I look at the web book and the PDF, the sidebar textboxes display right justified with text wrapped around them. 

See the McLuhan theme for an example. 

**Actual behaviour** 

I add a sidebar textbox in the visual editor from the Textboxes drop-down menu. It appears left justified. The surrounding text appears beneath the sidebar and does not wrap. When I look at the web book and the PDF, the side bars also appear left justified with no text wrapping.

Formats affected: Visual editor, web book, PDF

### Steps to reproduce the problem
1. Add any side bar textbox in the visual editor from the Textboxes drop-down menu. 
2. Add text content before and after the sidebar textbox.
3. In the visual editor, text appears above and below the side bar textbox, but does not wrap around the text itself. 
4. The web book and the PDF also show the side bar textbox without wrapped text.

### System Information

Development server

**Comment by bdolor** [comment]
thank you @josiegray — will take a look

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-textbook/commit/f093a2f764ca23f0803a42e04c44ba0c55bcd567
