### ISSUE TITLE
Textboxes not rendering Global options colours

### ISSUE THREAD

**Issue by pbstudent** [BCcampus/pressbooks-textbook#175]
### Description 

Textboxes not rendering Global options colours

**Expected behaviour** 

display correct colours

**Actual behaviour** 

no colours

### Steps to reproduce the problem

created a test page with text boxes.

### System Information

- Textbooks for Pressbooks: 4.1.2
- Pressbooks: 5.4
- WordPress: 4.9.7

**Comment by bdolor** [comment]
@pbstudent - more detail in steps to reproduce the problem will be helpful for next time.  

> create a test page with text boxes

Things work as expected for me. Is this happening in the wysiwg/dashboard or when viewing the book as a reader? Limited to web view or are you seeing this in exports? By global options colours, do you mean to go into 'theme options' change the value of 'Header Color' to a non-default colour? Is this behaviour happening on textboxes that were created previously or newly (after 4.1.2 update) created textboxes? Finally, does deactivating/reactivating the theme work to resolve this issue?

**Comment by pbstudent** [comment]
deactivating/reactivating the theme did not work
"behaviour happening on textboxes that were created previously or newly (after 4.1.2 update)...?"
- not certain, may be associated with 4.1.2/4.1.1

Sample of default Appearance > theme options > global options
![screenshot_2018-07-13 theme options mem pressbooks](https://user-images.githubusercontent.com/24277755/42715933-6e4db34e-86f9-11e8-8486-d945ad6ffc06.png)

Sample of editor view
![screenshot_2018-07-13 edit chapter mem pressbooks](https://user-images.githubusercontent.com/24277755/42715985-adaa196a-86f9-11e8-9937-6372432b12e2.png)

Sample of web view
![screenshot_2018-07-14 test page private mem](https://user-images.githubusercontent.com/24277755/42716002-c070be78-86f9-11e8-8eb5-2002681ffce5.png)

**Comment by bdolor** [comment]
@pbstudent would you confirm that you have the latest version of the parent theme McLuhan installed? https://github.com/pressbooks/pressbooks-book/releases

**Comment by pbstudent** [comment]
McLuhan 2.3 now updated to 2.4 
Editor view **has not changed changed**. However Web view has now changed to:
![screenshot_2018-07-14 test page mem](https://user-images.githubusercontent.com/24277755/42722992-a85b1886-8755-11e8-9626-d0dc465a6063.png)

**Comment by bdolor** [comment]
The textboxes are rendering as expected for me in both the dashboard and web view. Sometimes browser cache can play a role. Saving theme options or re-activating the theme can also trigger/force a rebuild.

**Comment by pbstudent** [comment]
Thanks that worked:
Activating another theme then reactivating Open Textbook theme for each book site resolved the editor view. Fortunately not hundreds of book sites.
