### ISSUE TITLE
download tracking event code for Google Analytics Universal upgrade?

### ISSUE THREAD

**Issue by JackDougherty** [BCcampus/pressbooks-textbook#18]
Brad, thanks for adding Google Analytics code for tracking download events. However, it's still not working for me, and I suspect that this may be caused by Google's recent upgrade from Classic to newer Universal Analytics:
https://developers.google.com/analytics/devguides/collection/upgrade/reference/gajs-analyticsjs

See also these references: 
http://stackoverflow.com/questions/25506115/does-not-display-track-record-in-google-analytics
and
http://stackoverflow.com/questions/26754109/google-analytics-universal-event-tracking-code-not-working

in line 98, you suggested that Google Analytics users insert this code:
```
$tracking = "_gaq.push(['_trackEvent','exportFiles','Downloads','$file_class']);";
```
This version did not work for me, probably because my GA accounts have all been updated from Classic to Universal. My understanding is that newer event code should follow this general format:
```
ga('send', 'event', 'category', 'action', 'opt_label', opt_value, {'nonInteraction': 1});
```
But I can't figure out the correct syntax to insert into your code. My failed attempts looked like this:
```
$tracking = "_ga(['send','event','exportFiles','Downloads','$file_class']);";
```
Can you point me in the right direction? Thanks.

**Comment by bdolor** [comment]
thanks Jack! https://github.com/BCcampus/pressbooks-textbook/commit/66de617f1ae600a33b3139e74e1640d204e5968d includes the GA Universal code that you sent via email.
