### ISSUE TITLE
Cover generator not working

### ISSUE THREAD

**Issue by josieg** [BCcampus/pressbooks-textbook#181]
### Description 

The cover generator doesn't seem to be working in any of the themes. There is an error message on the page that reads: "Some dependencies for Cover Generator exports could not be found. Please verify that you have completed the installation instructions." 
 
![covergen](https://user-images.githubusercontent.com/23706762/47112419-1eeb2400-d20b-11e8-9c35-b9d97ae7710e.JPG)

And the buttons used to generate a cover cannot be clicked.

![buttons](https://user-images.githubusercontent.com/23706762/47112459-3fb37980-d20b-11e8-9a49-0a8cff198db9.JPG)

**Expected behaviour** 

I add the information that I want on my book cover on the Cover Generator page in Pressbooks, and I can click "Make PDF Cover" or "Make Ebook Cover."

**Actual behaviour** 

I add the information that I want on my book cover on the Cover Generator page in Pressbooks, but when I try to generate a cover, the buttons to do so cannot be clicked. 

### Steps to reproduce the problem

1. Open a book's dashboard. Go to the Cover Generator page (under the Export tab).
2. Enter basic book information. 
3. Try to click "Make PDF Cover"

**Comment by bdolor** [comment]
The server dependencies required are installed, but may not have the correct/latest version. Not related to the plugin at all, but will leave it here. 

![image](https://user-images.githubusercontent.com/2048170/47113365-b3ef1c80-d20d-11e8-94cf-d9ef95d33bb0.png)

**Comment by bdolor** [comment]
resolved via https://github.com/pressbooks/pressbooks/pull/1467

**Comment by josieg** [comment]
I can create a PDF cover no problem, but when I try to generate an eBook cover I get the following error message:
![covergen.JPG](https://images.zenhubusercontent.com/5beb0ea53142e15bfe318405/10d583be-5fe6-4bf0-aaa6-6aeb4f8259b1)

**Comment by bdolor** [comment]
proposed resolution via https://github.com/pressbooks/pressbooks/pull/1474
