### ISSUE TITLE
Unable to import via web address, Pressbook XML file, EPUB, or Word

### ISSUE THREAD

**Issue by josieg** [BCcampus/pressbooks-textbook#186]
### Description 

Not sure where to report this, so let me know if it belongs elsewhere. I have tried multiple import methods and have been unable to get any of them to work.

**Expected behaviour** 

I expect to be able to import successfully, regardless of what file type or web page I am importing from.  

**Actual behaviour** 

No importing methods are working. 

### Steps to reproduce the problem

1. Create a new book in Pressbooks dev
2. Go to the Import page. 
3. Select an import option (I tried EPUB, web page, Pressbooks XML, and Word import options)
4. Upload the appropriate file type or add the correct web address depending on step 3 
5. Click "Begin import."
6. You are taken to a page to select what chapters and parts you want imported. Make you selections. 
7. Click "Import selection." The page refreshes, but nothing is imported and previous selections are removed. 

#### Book Info

Book ID: 226
Book URL: https://pressbooksdev.bccampus.ca/testingpb57/
Book Privacy: Public

#### Browser

Platform: Windows
Browser Name: Firefox
Browser Version: 66.0
User Agent String: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

#### WordPress Configuration

Network URL: http://pressbooksdev.bccampus.ca/
Network Type: Subdirectory
Version: 5.1.1
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.7.0
Book Theme: Open Textbooks
Book Theme Version: 2.1.5
Root Theme: Aldine
Root Theme Version: 1.6.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

CC Export for Pressbooks: 1.0.0
f5 Force SSL: 1.0.0
iThemes Security: 7.3.3
mPDF for Pressbooks: 3.3.0
Openstax Import for Pressbooks: 1.3.2
Pressbooks: 5.7.0
Pressbooks LTI Provider: 1.2.0
Pressbooks Stats: 1.6.2
Textbooks for Pressbooks: 4.2.3
WP-Matomo: 1.0.21

#### Book Active Plugins

CC Export for Pressbooks: 1.0.0
f5 Force SSL: 1.0.0
iThemes Security: 7.3.3
mPDF for Pressbooks: 3.3.0
Openstax Import for Pressbooks: 1.3.2
Pressbooks: 5.7.0
Pressbooks LTI Provider: 1.2.0
Pressbooks Stats: 1.6.2
Textbooks for Pressbooks: 4.2.3
WP-Matomo: 1.0.21

#### Inactive Plugins

Akismet Anti-Spam: 4.1.1
BC Post-Secondary Validator: 1.0.2
Candela Citation: 0.2.2
Candela Thin Exports: 0.1
H5P: 1.13.1
LTI: 0.1
WP QuickLaTeX: 3.8.6

#### Server Configuration

PHP Version: 7.1.27
MySQL Version: 5.5.5
Webserver Info: Apache

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 512M
Upload Max Size: 500M
Post Max Size: 500M
Upload Max Filesize: 500M
Time Limit: 60
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.19.7
imagick: Installed
xsl: Installed

**Comment by bdolor** [comment]
@josieg thanks for this - I _can_ recreate this on my local

**Comment by bdolor** [comment]
This was a long day looking for a one liner - should be fixed via https://github.com/BCcampus/pressbooks-textbook/commit/a922f4eca80e63f4cb52dfcb3df6499995dc95ba 

It came down to javascript files (import.js) not loading because of a call to a PB function in an admin_menu hook. Said hook/admin_menu is now gone and the import works. Will push out a release soon.
