### ISSUE TITLE
Pressbooks Textbooks breaks imports with PB 5.7

### ISSUE THREAD

**Issue by beckej13820** [BCcampus/pressbooks-textbook#187]
### Description 

On the final step of an import process when Pressbooks Textbooks is activated, we were returned to the same page without importing. Clicking import would redirect us to the screen which showed all of the chapters/parts.

**Expected behaviour** 

I'd expect to see the new taskbar with a slider and the time spent on the action.

**Actual behaviour** 

We end up in a loop. returning to the screen with the chapters/parts.

### Steps to reproduce the problem

This issue only occurs with the latest Pressbooks release 5.7 where they have updated the import screens.

Load a Pressbooks backup file from imports, select a few chapters, and click the begin import button.

(I can confirm disabling the plugin allows imports to work as expected.)

### System Information

- Textbooks for Pressbooks: 4.2.3
- Pressbooks: 5.7.0
- WordPress: 5.1.1

**Comment by bdolor** [comment]
Hi @beckej13820 - thanks for reporting. I have addressed this in https://github.com/BCcampus/pressbooks-textbook/issues/186 and can commit to a new release with the fix later today.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-textbook/releases/tag/4.3.0 - please feel free to re-open if it doesn't address the issue.
