### ISSUE TITLE
H3 being always centered

### ISSUE THREAD

**Issue by BakingSoda** [BCcampus/pressbooks-textbook#21]
Oh right, Thanks @bdolor. h3 being always centered can be solved at 
https://github.com/BCcampus/pressbooks-textbook/blob/dev/themes-book/opentextbook/style.css#L34
by selecting h3 as well.

**Comment by bdolor** [comment]
thanks @BakingSoda  — resolved in https://github.com/BCcampus/pressbooks-textbook/commit/dafac42f0790d1446bff8f9b6fc1093abbc99953 - will pull this change and others into our instance next week.
