### ISSUE TITLE
Search and import not importing

### ISSUE THREAD

**Issue by emasters** [BCcampus/pressbooks-textbook#22]
I'm running Wordpress 4.2.2 with Pressbooks 2.5 and PB Textbooks 1.2.8.
I'm using the search and import to search titles of chapters and books and that produces a list of chapters to import. I then select the chapters I'm interested and hit the start button. That quite quickly jumps me to the text organize dashboard page of the book but the chapters I selected for import are not visible in the list of posts included in the book.
I've checked my apache logs and found the following in the error log for the import part of the search and import transaction:
```[Sat Jun 20 12:16:16.746234 2015] [:error] [pid 27595] [client 64.134.28.106:50671] [ PBT Search and Import Log ]\nArray\n(\n    [time] => Sat Jun 20 12:16:16 2015\n    [site_url] => http://samplebook2.lawbooks.cali.org\n    [0] => Array\n        (\n            [171] => Array\n                (\n                    [type] => chapter\n                    [license] => cc-by-sa\n                    [author] => J.H. Verkerke\n                    [link] => http://verkerkecontractsone.lawbooks.cali.org/chapter/contract-formation/\n                )\n\n        )\n\n)\nTried to import a post from this PressBooks instance and succeeded :), referer: http://samplebook2.lawbooks.cali.org/wp-admin/admin.php?page=api_search_import```
Any ideas?

**Comment by bdolor** [comment]
Hi @emasters — thanks for the detail you have provided in your ticket. I looked at this briefly on my machine. I suspect it has something to do with the subdomain structure of the books in your collection. Likely something that can be addressed. I will endeavour to look at it in more detail on Monday.

**Comment by emasters** [comment]
Hi @bdolor Thanks for looking into this. The search and import feature was working on April 21, 2015 according to date stamps from post edits on a test book I was working on, if that helps at all.

**Comment by bdolor** [comment]
Potential fix is https://github.com/BCcampus/pressbooks-textbook/commit/776602f7beaf6583977808b3e420c92af9056f09 — Will you be able to test this prior to a new WP release? Do you update your PBT plugin via git, or strictly through the WP interface?

**Comment by bdolor** [comment]
Please feel free to re-open this ticket if the latest PBT release does not resolve the issue you were having. Thanks again @emasters

**Comment by emasters** [comment]
The fix works. Thank you @bdolor for getting to it promptly.
