### ISSUE TITLE
please add CSS PDF support for tight and loose tracking

### ISSUE THREAD

**Issue by JackDougherty** [BCcampus/pressbooks-textbook#23]
Thanks Brad for all of the work on PBT. When preparing your next update, please add CSS PDF support for tight and loose tracking, as described here:
http://guide.pressbooks.com/chapter/typhography-tight-and-loose-tracking/

**Comment by bdolor** [comment]
Hi Jack! 

This was committed to the code: https://github.com/BCcampus/pressbooks-textbook/commit/c85f9a66341907c5519dcacc81ee7b468d5dfdf7

**Comment by JackDougherty** [comment]
Thanks @bdolor for pointing out that change, which I overlooked.
