### ISSUE TITLE
bcc-box respresentation in mPDF output

### ISSUE THREAD

**Issue by sswettenham** [BCcampus/pressbooks-textbook#29]
div class="bcc-box bcc-success"
div class="bcc-box bcc-info"

Aforementioned code is displayed correctly in webpage output
![web_kt](https://cloud.githubusercontent.com/assets/360534/8630935/ee94e29e-2729-11e5-9f8f-5c9f9d087382.png)
and ePUB export
![epub_kt](https://cloud.githubusercontent.com/assets/360534/8630940/08b1f018-272a-11e5-954d-4c821309aeac.png)

However, mPDF output looses CSS in Title
![mpdf_kt](https://cloud.githubusercontent.com/assets/360534/8630949/1fba4f3a-272a-11e5-9302-8480b5eb12a4.png)

Is this a limitation of mPDF that will display correctly using PRINCE?

Thanks,
Steve

**Comment by bdolor** [comment]
This is, unfortunately, a limitation of the CSS that is currently supported in mPDF. This particular styling relies on the use of a pseudo selector `h3:first-child` which isn't supported in mPDF.

http://mpdf1.com/manual/index.php?tid=34

**Comment by sswettenham** [comment]
Thanks Brad,

Do you happen to know if this is supported in PRINCE?

Cheers,
Steve

**Comment by bdolor** [comment]
yes, it is supported: http://www.princexml.com/doc/selectors/
