### ISSUE TITLE
PDF download error on Visit Site page

### ISSUE THREAD

**Issue by sswettenham** [BCcampus/pressbooks-textbook#30]
Settings > PB Textbook > Redistribute tab >  Yes. I would like the latest export files to be available on the homepage for free, to everyone.

1. Export to PDF
2. Visit Site - Download PDF
3. Export > Trash PDF
4.Export >  Export to PDF (mPDF)
5. Visit Site
![dnloadformats](https://cloud.githubusercontent.com/assets/360534/8638349/82bfde5a-2875-11e5-8886-8f09dbac0cf3.png)
6. Download PDF > error: File not found: CREATIVE-CLINICAL-TEACHING-IN-THE-HEALTH-PROFESSIONS-1436712639.pdf

**Comment by sswettenham** [comment]
I have tested on a clean install of Pressbooks with same error:
1. Export Your Book page
2. Download Icon URL
http://../../../wp-admin/admin.php?page=pb_export&download_export_file=CREATIVE-CLINICAL-TEACHING-IN-THE-HEALTH-PROFESSIONS-1436720678._oss.pdf
3. Visit Site page
4. Download PDF icon URL
http://../../../open/download?filename=CREATIVE-CLINICAL-TEACHING-IN-THE-HEALTH-PROFESSIONS-1436720678&type=pdf

     error: File not found: CREATIVE-CLINICAL-TEACHING-IN-THE-HEALTH-PROFESSIONS-1436720678.pdf


Downloading in Export page works but not on public page.


Note: epub, xml export files work correctly

**Comment by sswettenham** [comment]
FYI
The following URL works with the appended ._oss :
http://../../../open/download?filename=CREATIVE-CLINICAL-TEACHING-IN-THE-HEALTH-PROFESSIONS-1436720678._oss&type=pdf

**Comment by bdolor** [comment]
fixed in https://github.com/BCcampus/pressbooks-textbook/commit/a18bb8f5ee619d1ccc3f607b7307b11ffbc53c26
Thanks for identifying the issue @sswettenham — will push out new version of the plugin in WP soon

**Comment by sswettenham** [comment]
validated - works - thanks,
