### ISSUE TITLE
Table of Contents not public

### ISSUE THREAD

**Issue by sswettenham** [BCcampus/pressbooks-textbook#32]
PressBooks v.2.5.2
PressBooks Textbook v.1.2.13

Table of Contents (TOC) Title is displayed but nothing else in public view.
In admin view, TOC is displayed correctly.
PUBLIC:
![toc-public](https://cloud.githubusercontent.com/assets/360534/8761935/d4d333ee-2d26-11e5-8acf-191c63e6b52d.png)

ADMIN:
![toc-admin](https://cloud.githubusercontent.com/assets/360534/8761936/dacd00a4-2d26-11e5-9049-7fc17ec57d1f.png)

**Comment by bdolor** [comment]
This is an issue that affects all themes and is not specific to PBT. It looks like it was introduced in [PressBooks recently](https://github.com/pressbooks/pressbooks/commit/f56418524acf3a6dfcdf60db40036b34907e933e) and I encourage you to open up a ticket there. 

Include in your description of the problem that anonymous (not logged in) users are not assigned a `has_cap` / capability role that would allow them to `read` a page, so any condition that checks for that will fail as seen:
https://github.com/pressbooks/pressbooks/commit/f56418524acf3a6dfcdf60db40036b34907e933e#diff-11dc803bb0b542aa987d37d504029e8fR20
https://github.com/pressbooks/pressbooks/commit/f56418524acf3a6dfcdf60db40036b34907e933e#diff-11dc803bb0b542aa987d37d504029e8fR37
https://github.com/pressbooks/pressbooks/commit/f56418524acf3a6dfcdf60db40036b34907e933e#diff-11dc803bb0b542aa987d37d504029e8fR54
https://github.com/pressbooks/pressbooks/commit/f56418524acf3a6dfcdf60db40036b34907e933e#diff-348c9f9580f4e8b34f5a0a3dcab76b8eR11
https://github.com/pressbooks/pressbooks/commit/f56418524acf3a6dfcdf60db40036b34907e933e#diff-348c9f9580f4e8b34f5a0a3dcab76b8eR44
https://github.com/pressbooks/pressbooks/commit/f56418524acf3a6dfcdf60db40036b34907e933e#diff-348c9f9580f4e8b34f5a0a3dcab76b8eR71
