### ISSUE TITLE
Search and Import

### ISSUE THREAD

**Issue by colomet** [BCcampus/pressbooks-textbook#34]
Dear sir:

My name is Toni Devís.

I´m the founder of on-lingua.com. A libre web site for learning second languages.

I want to use PressBooks with my books. And also pressbooks texbooks in one of my installation. Because i want to allow the people to download and share the content.

We have content in many languages, and we hope we will open the site soon. But we have now a problem with your plugin, because it´s easy to download our content from other site. 
<<
Search against the following domains.
(You can manage the list of domains to search against at any time:)
Reminder: You are responsible for adhering to all licensing and copyright restrictions.
>>

That is not a problem for the open content, but sometimes we have restrictet content (because we need also charge money some times to our users) . If somebody from other installation can download our premium content, we have not busines. And i think is it not fear for the users if they do not want to share

Can you make a modification and just autorice download a book or chapter if the material is under Creative Commons license, please and if is with copyright do not allow to download?.

thanks

**Comment by bdolor** [comment]
I understand the need to strike a balance between what is shared and what is private. The 'search and import' feature does provide discretion by respecting content that is marked 'private'. If the restricted content on your website is restricted by marking the book as 'private' in *Privacy -> Site Visibility* the API will not return results from that book domain. Also, if you have a book marked as 'public' in *Privacy -> Site Visibility* but in that book you have some chapters marked as 'private' or 'draft' the API will not return those chapters. In other words, the 'search and import' feature is expected to treat content/behave with the same discretion that is afforded when accessing content through a browser. If it does not behave that way, then it I will treat this as a bug and fix it. Please let me know if this alleviates your concern.

**Comment by colomet** [comment]
If i have a web site, it´s because i want to let the people to read my web site. If i do the content private, i have no busines.

I have maybe the first libre publishing company in the world. We will allow to download open resources, free resources and more. Afther years of development for the first integrated curriculum for the languages, also we are developing descriptors for many languages (our work it´s universiy grade, but we are not and we have not that funding) we are almost finishing the content.

We want to develop a place like BCcampus for languages. And because we have not public funding, we need to charge for some premium content. If many people use your plugin, they can literally import all the books without our permision and for free. We could close the company without open it. We need months of development for each book. 

But the problem is not just for us, also for other people. Pressbooks is available for many people from diferent situations. If a writer is working with pressbooks, he could lose the control of ther book.

We use pressbooks because your plugin. Also we are developing educational tools for pressbooks https://github.com/On-lingua. because we want to make more educational ready pressbooks.  With pressbook texbooks we can easy to make possible the ALMS Framework http://www.opencontent.org/definition/ but again, it have to be our choice, what to share and how to share.

Open movement means, if the autor want to share, it´s the autor right. Not dutty. You can download with google image, but with images we can use watermarks, what we will do with books?.  With your plugin, the balance is in the direction of the people, but what about the autor? You allow the people to stole the original copies of the books, even if is not under Creative Commons.

I know other informatician can do a plugin and stole the content, but you allow to do it to general people without code skills. 

In PressBooks i chose which chapters i can export or not. In the same way it should work <<search and import>>.
 But i think the best way it will be allow to import just books with Creative Commons license.

I love the funcionality, i love your plugin, but i think you should change it a litle for the common best.

I hope you undestand my problem.

**Comment by colomet** [comment]
and also, why i can download from other pressbooks installation and not from pressboos.com?. thanks

**Comment by bdolor** [comment]
The argument that developers should be held accountable for what other people choose to do with their free tools is a dubious one at best. If someone builds a hammer, gives it away for free and someone else decides to use it to break down a door, the creator of the hammer is not responsible for the damage to the door. Likewise, the developers of 'copy and paste' are no more responsible for the theft of copyrighted works than I am creating an API that accesses public information about a public website. 

That said, I do understand your problem, but I don't have all the details of how you're implementing restricted access to content. Anytime I have created a website that displays restricted content to authorized (paying) customers only, authentication is necessary. I need to know who you are and if you've paid and only then will you be able to view the content. If you set a book/chapters as private, only authenticated users (subscribers, for instance) will be able to see your content. If the book/chapters are set to private, the API won't touch it. That seems like a pretty solid way to implement the business model that you're after. So if you're not doing it that way, why not? How are you implementing access to restricted content to paying customers?

**Comment by colomet** [comment]
for my company, i have in mind several options for the restricted acces. In the earlier version, i would like not to have to use it. For me, i think i can handle, i have to chose what is for the world and what is for my premium users. It´s a problem but i can handle. But i think i should have the right to chose if i want to allow download or not.

But about the plugin. Right now, you can find several options if you want to import content from one wp blog to another, for all of that options, you need the autorization from the owner of the blog (with a key) With your plugin, is not necesary. Everybody can download a book.

Is not like a Hammer, is like a master Key. If you are living in a flat, with community areas, i´m sure you want to allow your friend to go there and play tenis, or swimm. But i´m sure you will never give them the key of your house, at least not all of them, just the people you trusth. O in a specific moment. I´m sure your friends will never open your house without your permision and they will never do nothing wrong with the house, but, remember, everybody have the key of your hourse, your friends, and the friends of your neigbours, and also the people from the other side of the city. Do you trusth them?

That is the problem here. You believe you can trusth with everybody. I think it have to be the choice of the autor of the content, decide to who deserve the key or not. If the writer decide to open to the world. It´s great. As i tell you, the most of my content it will be open. But not all of them.

Now, with your plugin and pressbooks, you can download for free the books, but the owner of the book have so set to export each chapter the owner want to share with the world. If some of them are just open for read but he do not want to allow to download, is the choice of the writer.

Is complicate to develop the same system for the import feature of your plugin?

All of the situations i know for download content from a wordpress installation, have a security system. I´m sure.

My company is Creative Commons friendly, but because i chose. If i decide not to allow download a chapter, have to be my choice.

with your plugin, there is not such choice anymore if you want to import. If i want for me the book, it have to be private. I think is too drastic choice. And also if i do not offer the book as Creative Commons license, i think is illegal to download the content, because you have no my permision, you allow to do illegal download from your plugin, and it can not be upload to wordpress.org. Had you thought of that?

Thanks for your time.

**Comment by bdolor** [comment]
I don't disagree with you at all that downloading someone's copyrighted material is illegal and I don't condone it. I disagree with you entirely about where you're willing to point the finger. 

Whatever the metaphor, the maker of keys or hammers is not responsible for somebody's choice to to use those tools in ways for which they are not intended. This tool is not designed, marketed or intended to steal other people's works, and has gone to great lengths to ensure licensing and attribution are respected, or at the very least observed. By all estimations it is free and clear from any copyright infringement that could be fathomed in the most fear-mongering of minds. If I'm wrong about that and you're still not willing to protect your author's works behind an established authentication mechanism, then there are hundreds of repositories you should start investigating for similar infractions. https://github.com/search?q=screen+scraper&type=Repositories&utf8=%E2%9C%93 

This is a tool that has been made for a specific purpose (openly licensed textbooks) and released in the hopes that it will benefit others. I am glad to hear this free software is benefiting your business. All pull requests are happily considered. 

To dispel any further concerns, I have excluded any search results that are marked as 'all-rights-reserved'. https://github.com/BCcampus/pressbooks-textbook/commit/852cd7ecceafa52f3843b1b8ac68df7cf8f3cee2 Next time, a pull request will do. Thanks!
