### ISSUE TITLE
Large tables not displaying correctly in Site visit and epub export

### ISSUE THREAD

**Issue by ghost** [BCcampus/pressbooks-textbook#39]
Wordpress 4.3
Pressbooks Version 2.7.1
PressBooks Textbook Version 1.2.15

-------------
Visit Site display extends beyond body of text:
![html-table_1_lg](https://cloud.githubusercontent.com/assets/360534/9559543/00d945b6-4dc3-11e5-8a6d-71ad6b69f159.png)
 
EPUB display cuts off table content:
![epuf-table_1_lg](https://cloud.githubusercontent.com/assets/360534/9559545/188b4470-4dc3-11e5-8a39-6ed86a4da9ab.png)

No issue with mPDF rendering
![pdf-table_1_lg](https://cloud.githubusercontent.com/assets/360534/9559553/3f677618-4dc3-11e5-8662-80b45c28fd02.png)
-------------
PRESSBOOKS . COM site outputs Visit Site display correctly as a horizontal scroll:
![2015-09-13_11-03-42](https://cloud.githubusercontent.com/assets/360534/9839261/1432a50e-5a74-11e5-88b7-5d0c48fe8b95.png)
-------------

Research links:
Responsive Data Tables - https://css-tricks.com/responsive-data-tables/
How to Create Responsive Tables in WordPress - http://exisweb.net/responsive-tables-in-wordpress
10+ Solutions for Responsive Data Tables - http://exisweb.net/responsive-table-plugins-and-patterns

-------------
Workaround for epub display seems to be converting large tables into images with link to larger content.

or

The following appears to be a potential solution for Site visit display:

Themes > Editor > Open Textbooks > style.css > #content table {

CHANGE display:table to block

Example:
/*******************************
	Textbook specific styles 
********************************/

#content table {
	border-spacing: 0;
        display: block;
}

**Comment by sswettenham** [comment]
Following plugin prevented tables from breaking the PTextbook responsive layout:
 Responsive Scrolling Tables

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-textbook/commit/726561a575090b9e10e648394c2d171e61ac3e17
