### ISSUE TITLE
Check minimum PB requirements before trying to load plugin

### ISSUE THREAD

**Issue by connerbw** [BCcampus/pressbooks-textbook#43]
Hi, can you include this snippet (or something similar) above [Line 403 in pressbooks-textbook.php](https://github.com/BCcampus/pressbooks-textbook/blob/dev/pressbooks-textbook.php#L403) please?

```php
// Minimum PB requirements
if ( ! @include_once( WP_PLUGIN_DIR . '/pressbooks/compatibility.php' ) ) {
    add_action( 'admin_notices', function () {
        echo '<div id="message" class="error fade"><p>' . __( 'Cannot find Pressbooks install.', 'pressbooks' ) . '</p></div>';
    } );
    return;
}
elseif ( ! pb_meets_minimum_requirements() ) {
    return;
}
```

It's a [new file](https://github.com/pressbooks/pressbooks/blob/dev/compatibility.php) that can be used for plugins that depend on the PB plugin. It will prevent PBT from running if a user upgrades and gets bitten by the PHP version change in the next release.

**Comment by bdolor** [comment]
complete as per https://github.com/BCcampus/pressbooks-textbook/commit/70c03eb3c620e74db6e7dd9d50b016feb51d7b23
