### ISSUE TITLE
Upgraded to Pressbooks-textbook 2 with following site error

### ISSUE THREAD

**Issue by sswettenham** [BCcampus/pressbooks-textbook#44]
Pressbooks 3

Notice: Undefined index: pb_bisac_subject in /var/www/html/wp-content/plugins/pressbooks-textbook/themes-book/opentextbook/functions.php on line 81

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-textbook/commit/58e857a90faf3c14d5d1c5f6f3182206d8ebfb0b
