### ISSUE TITLE
Two Different Book Info pages

### ISSUE THREAD

**Issue by sswettenham** [BCcampus/pressbooks-textbook#45]
The source of the issue is with the pressbooks-textbook plugin:
1. starting on ../wp-admin/options-general.php?page=pressbooks-textbook-settings
2. select Book Info link in "Two easy steps, using built-in functionality (recommended)
    Select your 'Copyright license' from the drop down menu in the Copyright section on the Book Info page."
3. goes to a blank info page (/wp-admin/wp-admin/post-new.php?post_type=metadata) - saving this page will delete previous book info

**Comment by bdolor** [comment]
Thank you for noticing and reporting this. Resolved via https://github.com/BCcampus/pressbooks-textbook/commit/17c0ca7b95aa930ab1c4abaf3b5b5d5ca2d5bc00
