### ISSUE TITLE
PHP error message when installing Pressbooks-Textbook v.2

### ISSUE THREAD

**Issue by sswettenham** [BCcampus/pressbooks-textbook#46]
Re-posted from (https://github.com/pressbooks/pressbooks/issues/303)

MESSAGE
"... can be overridden, so long as it is remains above PHP 5.4.0. Add a line to wp-config.php as follows: $pb_minimum_php = 5.4.0; "

Needs quotes ???

     $pb_minimum_php = '5.4.0';

https://github.com/BCcampus/pressbooks-textbook/blob/aa8af8d49e7e3344a974466b542ee9aeb2dc4589/pressbooks-textbook.php#L417

**Comment by bdolor** [comment]
Thanks! Resolved via https://github.com/BCcampus/pressbooks-textbook/commit/9fe2d46dc225ed073990316d3ff5db30f0289305
