### ISSUE TITLE
Webpage Table of Contents not linked to sub-headings

### ISSUE THREAD

**Issue by sswettenham** [BCcampus/pressbooks-textbook#47]
Tested: WP 4.4 + PB 3.0 + (all default themes + PBTextbook)
Parse Sections Enabled a two-level TOC

Result: TOC working correctly on pointing to subheadings except PBTextbook theme

PBTextbook Result - link of sub-heading goes to top of page, not to 2nd level heading.

Example of issue: http://epub-fhd.athabascau.ca/clinical-teaching

**Comment by bdolor** [comment]
thank you! resolved via https://github.com/BCcampus/pressbooks-textbook/commit/135d13882c283a746681dbb9baa6236c4cc4714d
