### ISSUE TITLE
EPUB and MOBI EXPORT errors

### ISSUE THREAD

**Issue by sswettenham** [BCcampus/pressbooks-textbook#52]
WP 4.4.1, BP 3.1.2, PBT 2.1.2

Some interesting errors output on EPUB and MOBI exports, that I have not seen before:

**MOBI** - Amazon kindlegen(Linux) V2.9 build 1028-0897292

CSS style specified in content is not supported by Kindle readers. Removing the CSS property: 'max-width' in file: /tmp/mobi-d98Che/OEBPS/open-textbooks.css

Please use % or refer Kindle Publishing Guidelines about usage of property: 'line-height' in file: /tmp/mobi-d98Che/OEBPS/chapter-001-slug-1-introduction.xhtml

**EPUB3**

ERROR(RSC-007): /var/www/html/wp-content/uploads/sites/3/exports/e-Textbook-Reflections-1453987136._3.epub/OEBPS/open-textbooks.css(23,9): Referenced resource could not be found in the EPUB

**Comment by bdolor** [comment]
I noticed some new errors once sass was introduced for the parent theme. They aren't affecting the outcome of epub so are low priority. They are noted and will be attended to once OTB theme moves over to sass. Closing for now.
