### ISSUE TITLE
Theme Options and mPDF TOC issue found

### ISSUE THREAD

**Issue by ghost** [BCcampus/pressbooks-textbook#53]
WP 4.2.2, PB 3.1.2, PBT 2.1.2, PmPDF 1.0.1

Symptom:
No TOC generated with PDF even though all system configurations are correct.

Workaround Solution:
Go to Open Textbook Theme Options > mPDF Options tab > Table of Contents > disable,  then Save Changes, then re-enabled

Now generates TOC in PDF

Circumstances when this happens:
Migrating from one server to another.  Everything appears fine across Pressbooks system and sites, except TOC is not generated in PDF.

**Comment by sswettenham** [comment]
Also found same symptom on BCcampus Pressbooks.

**Comment by bdolor** [comment]
resolved via https://github.com/pressbooks/pressbooks/pull/402
