### ISSUE TITLE
not seeing option for Textbook theme in WP PB install

### ISSUE THREAD

**Issue by jeremydean** [BCcampus/pressbooks-textbook#54]
I doubt this is a truly github worthy "issue" but I'm trying to get set up with the PressBooks TextBook plugin/theme.

I set up a multisite WordPress install and installed the PressBooks plugin successfully (I believe). I see the basic PB WP themes available and have created a book.

http://jeremydean.org/pressbooks/ananthologyofmyown/

http://jeremydean.org/pressbooks/ananthologyofmyown/chapter/chapter-1/

I've added the PB Textbook plugin and network activated it.

BUT I'm not seeing the "Textbook theme" available at the network or book appearance admin levels.

Again, apologies that this is not likely a bug/feature issue, but any support would be appreciated. 

I work with professors who want to do have annotatable PressBooks and want to be able to properly guide them through the process.

**Comment by bdolor** [comment]
At the very least, this gives us more than 140 characters to walk through some scenarios. I just took myself through setting up and installing a new instance of PB and PBT to see if I could recreate the issue, but everything worked as expected. 

There shouldn't be any trickery involved in getting the theme to show up, so my suggestions won't be very ground breaking. Low hanging fruit is eliminating browser cache, deactivating/re-activating the plugin...if it's not at the application or browser level, then looking at the server level could involve checking file permissions, directory structure. 

Wish I could be of more help.

**Comment by jeremydean** [comment]
thanks for your response, brad. i'm sure i've done something very basic wrong. this is my first time digging this deep into this kind of territory.

one thing i'm noticing is that the textbook theme--and the normal PB themes--are not in the themes folder at the WP level. don't know if that's expected/helps.

thanks, again, for your time.

**Comment by bdolor** [comment]
both PB and PBT place themes within their own plugin directories, so nothing out of the ordinary.

**Comment by jeremydean** [comment]
So, with PB and PBT network active, 

https://dl.dropboxusercontent.com/u/17407226/Jing/2016-02-12_1502.png

I should see the PBT theme in themes at the network level and book level?

https://dl.dropboxusercontent.com/u/17407226/Jing/2016-02-12_1503.png

**Comment by bdolor** [comment]
Correct, you should be seeing the theme Open Textbooks at the Network level: 
![screen shot 2016-02-12 at 1 05 41 pm](https://cloud.githubusercontent.com/assets/2048170/13020314/919d7a28-d189-11e5-8ffd-5de1b53eecd8.png)

and at the book level as well: 

![screen shot 2016-02-12 at 1 09 03 pm](https://cloud.githubusercontent.com/assets/2048170/13020361/cfed3dae-d189-11e5-9deb-213e8c799119.png)

**Comment by jeremydean** [comment]
so moving the textbook theme folder into the general theme directory for my site i was able to see the former option, but was never able to create it at the book level.

do you think maybe there's something wrong/missing with my original PB install? should i deactviate and/or trash it and start again? (already did this once with PBT.)

thanks, again, for your time/support. i'm psyched to get textbooks running and plan to blog about it.

**Comment by jeremydean** [comment]
ps. do my PB themes need to be disabled at network level to see/activate the textbook theme? (as pictured in your screenshot.)

**Comment by jeremydean** [comment]
i went ahead and deactivated both PB and PBT. and then reactivated both and now everything appears fine. sorry for bugging you with something so simple as turning it off and on again.

**Comment by jeremydean** [comment]
but how do i activate hypothes.is? (sorry/thanks!)
