### ISSUE TITLE
add bibliographic metadata to textbooks 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-textbook#55]
include metadata for a book as per guidelines https://scholar.google.ca/intl/en/scholar/inclusion.html#indexing

**Comment by JackDougherty** [comment]
+1
I've been using the old ScholarPress COinS plugin to make my PBT sites more Zotero-friendly.
https://wordpress.org/plugins/scholarpress-coins/
But I'm never happy with the way that plugin mistakenly categorizes pb_author etc. metadata, so am looking forward to a new method.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-textbook/commit/4cd1aea3624cb1829b40ecffb0bd4bd32f9c6f88
