### ISSUE TITLE
Various export issues

### ISSUE THREAD

**Issue by thomaswking6** [BCcampus/pressbooks-textbook#57]
Wordpress version 4.42
Pressbooks version 2.5
Pressbooks textbooks version 1.28

**Issues**
A) Cell colours in tables do not render in: 
   1) standard display: https://drive.google.com/file/d/0B90-KHEjN4KVU2NBV1dYUG0walU/view?usp=sharing   
   2) odt export: https://drive.google.com/file/d/0B90-KHEjN4KVSGd2WXg1cDBGV1k/view?usp=sharing 

B) Table width scaled to fit table contents, not page width:
   1) epub: https://drive.google.com/file/d/0B90-KHEjN4KVYzdva2hvOXN5UVE/view?usp=sharing 
   2) odt: https://drive.google.com/file/d/0B90-KHEjN4KVak9wcGd5OGMwQlE/view?usp=sharing 
   3) Xhtml: https://drive.google.com/file/d/0B90-KHEjN4KVRFVESkRqbjNjanM/view?usp=sharing

C) Footnotes not rendering in xhtml version

D) <ol> lists not rendering in mpdf export: 
   1) https://drive.google.com/file/d/0B90-KHEjN4KVeDM4Nm9PV0RObms/view?usp=sharing 

E) Figures not appearing in odt export
blob:https://drive.google.com/351c665b-a970-4066-9908-82b382db6f14

**Comment by thomaswking6** [comment]
Apologies for premature post. Some errata:

1) html underpinning issue 1): 
<table bgcolor="#00FF00">, which does display fine on the html and epub exports:
https://drive.google.com/file/d/0B90-KHEjN4KVRFVESkRqbjNjanM/view?usp=sharing 
https://drive.google.com/file/d/0B90-KHEjN4KVYzdva2hvOXN5UVE/view?usp=sharing 

2) Issue E - correct image url is https://drive.google.com/file/d/0B90-KHEjN4KVak9wcGd5OGMwQlE/view?usp=sharing

**Comment by bdolor** [comment]
Hi, thanks for letting me know about the issues you've come across. Updating your plugins to the latest version will put us both on the same page and let us troubleshoot any issues that remain. Otherwise we  find ourselves chasing after problems that have (potentially) already been dealt with.

Pressbooks is currently at 3.2.0
Pressbooks Textbooks is at 2.1.2

**Comment by bdolor** [comment]
closing for now, please re-open if you discover these issues in the latest versions. Thanks!
