### ISSUE TITLE
Ordered List Rendering

### ISSUE THREAD

**Issue by lane-bmc** [BCcampus/pressbooks-textbook#58]
A few issues with rendering ordered lists (and nested OLs) and the discrepancies between Pressbooks preview and browser rendering.

The following is the code used:
<ol>
	<li>Why do economists use the <em>ceteris paribus</em> assumption?</li>
	<li>In an analysis of the market for paint, an economist discovers the facts listed below. State whether each of these changes will affect supply or demand, and in what direction.
<ol type="a">
	<li>There have recently been some important cost-saving inventions in the technology for making paint.</li>
	<li>Paint is lasting longer, so that property owners need not repaint as often.</li>
	<li>Because of severe hailstorms, many people need to repaint now.</li>
	<li>The hailstorms damaged several factories that make paint, forcing them to close down for several months.</li>
</ol>
</li>
<li>Many changes are affecting the market for oil. Predict how each of the following events will affect the equilibrium price and quantity in the market for oil. In each case, state how the event will affect the supply and demand diagram. Create a sketch of the diagram if necessary.
<ol type="a">
	<li>Cars are becoming more fuel efficient, and therefore get more miles to the gallon.</li>
	<li>The winter is exceptionally cold.</li>
	<li>A major discovery of new oil is made off the coast of Norway.</li>
	<li>The economies of some major oil-using nations, like Japan, slow down.</li>
	<li>A war in the Middle East disrupts oil-pumping schedules.</li>
	<li>Landlords install additional insulation in buildings.</li>
	<li>The price of solar energy falls dramatically.</li>
	<li>Chemical companies invent a new, popular kind of plastic made from oil.</li>
</ol>

A screenshot from the PressBooks Visual panel view of this code:
![image](https://cloud.githubusercontent.com/assets/14902378/14691604/f17bac6e-0706-11e6-8f03-1ed1bfcd8323.png)

A screenshot from the rendered version (same in all major browsers) of this same code:
![image](https://cloud.githubusercontent.com/assets/14902378/14691631/2668b886-0707-11e6-87dd-1d593b936736.png)

**Issues**
The rendered browser version lacks hanging indents, and when nesting the lists there isn't enough space to differentiate between the two levels of hierarchy.

Also, rendering seems to not like the lettered lists, and converts them all to numbers (e.g. a, b, c becomes 1.1, 1.2, 1.3) despite the inline code stating otherwise.

**Comment by bdolor** [comment]
thanks @lane-bmc  — will take a look

**Comment by lane-bmc** [comment]
One more issue found - nesting unordered lists inside ordered lists seems to produce bullet points with both bullet points and numbering.

Code used:

```
<ol>
	<li id="fs-idm19487600">To compute the amount spent on each fruit in each year, you multiply the quantity of each fruit by the price.
<ul id="fs-idm60615088">
	<li>10 apples × 50 cents each = $5.00 spent on apples in 2001.</li>
	<li>12 bananas × 20 cents each = $2.40 spent on bananas in 2001.</li>
	<li>2 bunches of grapes at 65 cents each = $1.30 spent on grapes in 2001.</li>
	<li>1 pint of raspberries at $2 each = $2.00 spent on raspberries in 2001.</li>
</ul>
```

Intended look:

> <ol>
	<li id="fs-idm19487600">To compute the amount spent on each fruit in each year, you multiply the quantity of each fruit by the price.
<ul id="fs-idm60615088">
	<li>10 apples × 50 cents each = $5.00 spent on apples in 2001.</li>
	<li>12 bananas × 20 cents each = $2.40 spent on bananas in 2001.</li>
	<li>2 bunches of grapes at 65 cents each = $1.30 spent on grapes in 2001.</li>
	<li>1 pint of raspberries at $2 each = $2.00 spent on raspberries in 2001.</li>
</ul>

Actual rendering:

![image](https://cloud.githubusercontent.com/assets/14902378/14865631/535cbabe-0c74-11e6-804c-278c54ac49a5.png)

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-textbook/commit/126d7536162addb5227b8ae7380f020c59afd35f and https://github.com/BCcampus/pressbooks-textbook/commit/baaf0d4f4e6f82b3287f38d26170011beeedd698
