### ISSUE TITLE
Pressbook formats

### ISSUE THREAD

**Issue by ausapa** [BCcampus/pressbooks-textbook#59]
Hello
After updating Pressbook Textbook download formats options disappeared. I'm using the pluging with wordpress with the last version.
Does anybody know how to solve this issue?
Thanks so Much
Aureliano

**Comment by bdolor** [comment]
Hello,
could you provide more information about your issue? I feel like there isn't enough information provided to recreate the problem myself, or be of much help to you. 

What version were you upgrading from?
What version were you upgrading to? 
What error messages were thrown? 
Do you have screen shots of what it looks like now? 
If I were to re-create this on my machine, what steps would I need to follow to produce the same behaviour?

**Comment by ausapa** [comment]
Hello
Download in the following formats:
epub, pdf ....
And if shows all of the formats I have published.
But after update, it shows nothing to download.
Current version Version 3.1.2 
Version to be updated  3.4.0
Wordpress version  4.5.1

Thanks so much 
Aureliano

**Comment by bdolor** [comment]
okay - those look like Pressbooks Version numbers, not Pressbooks Textbook version numbers. 

Please confirm: 
1. What theme you are using
2. If you've exported the book to different file formats
3. What your settings are in Settings->PB Textbook (Share Latest Export Files)

![screen shot 2016-05-04 at 10 49 46 am](https://cloud.githubusercontent.com/assets/2048170/15023682/538d1124-11e6-11e6-8b29-891516958550.png)

**Comment by ausapa** [comment]
Hello
Theme Textbook
PB Textbook (Share Latest Export Files)
And I sport epub, pdf (using Mpdf)
The exported files do not appear on the online book reading.
Thanks so much
Aureliano

**Comment by bdolor** [comment]
OK — I've chased down this issue, which is related to an upgrade with PB, not PBT and will be addressed with this ticket: https://github.com/pressbooks/pressbooks/issues/401 The symlink didn't make it through in PB 3.4.0 so when PB releases a new version with the symlink included, the images will reappear.

**Comment by bdolor** [comment]
Removing dependency on symlink via: https://github.com/BCcampus/pressbooks-textbook/commit/baa86909a3c12d94658ac1d3b923c3f1de1da13a

**Comment by ausapa** [comment]
Hello
Ok
Thanks so much
Aureliano
