### ISSUE TITLE
Image caption: font type and position

### ISSUE THREAD

**Issue by laesoph** [BCcampus/pressbooks-textbook#69]
The font and styling for the image caption in the web version is different from the PDF. The font in the PDF is in italics. Can both font types be the same type AND not italicized.

Also, the image caption text is centred on the online version, but left-aligned in the PDF. Please make both versions left-aligned.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-textbook/commit/b666b7fe423bc78c84bdfa0aed8fe9508f118dde
