### ISSUE TITLE
Greek and Latin Roots open textbook: request access to Greek and Latin fonts

### ISSUE THREAD

**Issue by laesoph** [BCcampus/pressbooks-textbook#70]
"Greek and Latin Roots" (https://pressbooks.bccampus.ca/greeklatinroots) requires access to Greek and Latin fonts (now available through Language Support in the Clark theme). This "Greek and Latin Roots" open textbook is being written using the Open Textbook theme. Please give these authors access Greek and Latin fonts in this book.

**Comment by laesoph** [comment]
Part two: another language support request. This is for "Knowing Home" (https://pressbooks.bccampus.ca/knowinghome/wp-admin/), a book that uses several indigenous languages and needs font support both in the text body and, if possible, in the chapter title fields.

So far the project manager at U.Vic. has reported that the below languages are being used. This information came from the author. There might be more.

1. Kwak̕wala / Kʷak̓ʷala (Kwakiutl)
2. Nisg̱a’a (Nishga)
3. SENĆOŦEN (Straits Salish)
4. Tsilhqot’in (Chilcotin)
5. Haida

The most commonly used characters/fonts used for the above languages are listed on the attached PDF.



[Indigenous fonts for Knowing Home.pdf](https://github.com/BCcampus/pressbooks-textbook/files/559373/Indigenous.fonts.for.Knowing.Home.pdf)

**Comment by bdolor** [comment]
Thanks @laesoph — This is a good start. I will use the languages listed as a reference to search out font files that support those.

**Comment by laesoph** [comment]
For each of the above books, the author would also like to:
- use these fonts (Greek, Latin, or First Nations) in the Chapter and Parts title fields
- allow fonts used as Heading 1 to display correctly in the table of contents

**Comment by bdolor** [comment]
Greek and Latin font coverage is available via https://github.com/BCcampus/pressbooks-textbook/commit/613b427178499b603f162f0b8ae3e5d26bec763e  

closing this issue, moving Indigenous Language request to a new issue.
