### ISSUE TITLE
CSS warnings/errors in PDF and EPUB formats

### ISSUE THREAD

**Issue by josieg** [BCcampus/pressbooks-textbook#71]
When exporting the Introduction to Psychology: 1st Canadian edition, the following warnings/errors were emailed out by Pressbooks:
**For the PDF:**
Wed Nov 23 09:43:37 2016: /tmp/phpvppV7A:12: warning: missing media condition
Wed Nov 23 09:43:37 2016: /tmp/phpvppV7A:12: warning: parse error in media query at '"textboxes"'
Wed Nov 23 09:43:37 2016: /tmp/phpvppV7A:14: warning: unknown '@mixin' rule
Wed Nov 23 09:43:37 2016: /tmp/phpvppV7A:810: warning: unknown '@include' rule
Wed Nov 23 09:43:37 2016: /tmp/phpvppV7A:1109: warning: unknown '@include' rule
Wed Nov 23 09:43:37 2016: /tmp/phpvppV7A:1452: warning: unknown page class ':after'
**For the EPUB:**
ERROR(RSC-007): /var/www/webapps/pressbooks/wp-content/uploads/sites/9/exports/Introduction-to-Psychology-1st-Canadian-Edition-1479926350.epub/OEBPS/open-textbooks.css(21,9): Referenced resource could not be found in the EPUB.

**Comment by bdolor** [comment]
Thanks for reporting the issue @josieg 👍

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-textbook/commit/613b427178499b603f162f0b8ae3e5d26bec763e
