### ISSUE TITLE
Indenting

### ISSUE THREAD

**Issue by acoolidge** [BCcampus/pressbooks-textbook#76]
This is ONLY in the onscreen HTML version:

Throughout Hospitality and Tourism: https://opentextbc.ca/introtourism/chapter/chapter-7-travel-services/ ... the first paragraph is not indented, followed by indented paragraphs.

See screen shots:
![screen shot 2017-01-16 at 8 47 30 am](https://cloud.githubusercontent.com/assets/23705492/21992197/61403342-dbca-11e6-918c-629d705f7504.png)
![screen shot 2017-01-16 at 8 43 36 am](https://cloud.githubusercontent.com/assets/23705492/21992196/613d678e-dbca-11e6-8f09-fb0c3a3a500f.png)
![screen shot 2017-01-16 at 8 41 38 am](https://cloud.githubusercontent.com/assets/23705492/21992198/6140d1d0-dbca-11e6-97f7-96c368b73b24.png)

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-textbook/commit/0f88d20c26dad5c71020d2fb44ce05f5366affe8 

note: you will likely have to clear browser cache to see the difference
