### ISSUE TITLE
Heading 1 all caps in print PDF

### ISSUE THREAD

**Issue by laesoph** [BCcampus/pressbooks-textbook#78]
In the Greek and Latin Roots, part I Latin, Heading 1 is all caps in the Front Matter in print PDF, digital PDF and web view.

I compared this to the print PDF before the change which does not do this.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-textbook/commit/0f88d20c26dad5c71020d2fb44ce05f5366affe8
