### ISSUE TITLE
Unknown numbers in table of contents of PDF

### ISSUE THREAD

**Issue by laesoph** [BCcampus/pressbooks-textbook#80]
In the Greek and Latin, part I book, in the Main Body table of contents in PDF,
- there is "1." positioned to the left of chapter part "52. What is a Diminutive?"

In the Back Matter (Appendices)
- there is "2." positioned to the left of "I. Key to Exercises (Latin)"
- there is "3." positioned to the left of "II. Summary of Vocabulary Tables (Latin)"

These numbers do not appear in the edit or reading view of the web version

**Comment by bdolor** [comment]
Aside from part numbering, which is being addressed by PB in https://github.com/pressbooks/pressbooks/commit/f3ad46a0607115499761fede41adb749ddf3842b can the display of chapter numbers not be controlled in Theme Options->Global Options?

**Comment by bdolor** [comment]
closing.
