### ISSUE TITLE
Random ? in PDF

### ISSUE THREAD

**Issue by acoolidge** [BCcampus/pressbooks-textbook#82]
See attachment, page 117 of 376
![screen shot 2017-01-16 at 9 42 16 am](https://cloud.githubusercontent.com/assets/23705492/21993543/26843a68-dbd0-11e6-929a-97788d3a9868.png)

**Comment by bdolor** [comment]
- There is no attachment
- This looks like a content related problem, perhaps a quotation mark or other character that is not recognized and defaulting to a `?` 
![image](https://cloud.githubusercontent.com/assets/2048170/21994545/13074976-dbd5-11e6-847f-356a5319a922.png)

- Likely not theme related.
