### ISSUE TITLE
Font error in PDF

### ISSUE THREAD

**Issue by acoolidge** [BCcampus/pressbooks-textbook#83]
Heading code repeated in paragraph in PDF- page 261 of 376
![screen shot 2017-01-16 at 9 57 54 am](https://cloud.githubusercontent.com/assets/23705492/21994003/77f12594-dbd2-11e6-840c-effc93234ab7.png)

**Comment by bdolor** [comment]
Could you provide a bit more information on this? Is this an error in content or theme related?
