### ISSUE TITLE
Exercises and Textboxes not showing

### ISSUE THREAD

**Issue by acoolidge** [BCcampus/pressbooks-textbook#84]
Table format is less clear and textboxes don't show up for exercises and review questions
![screen shot 2017-01-17 at 8 33 09 am](https://cloud.githubusercontent.com/assets/23705492/22029541/b254a216-dc8f-11e6-9c5f-5c1007005b97.png)
![screen shot 2017-01-17 at 8 34 07 am](https://cloud.githubusercontent.com/assets/23705492/22029550/bc99cd50-dc8f-11e6-8a70-d1393b377fec.png)

https://opentextbc.ca/physicalgeologyjosie/chapter/chapter-11-earthquakes/

**Comment by bdolor** [comment]
The reason for this is because the new theme hadn't compiled. 

Resolved. 🔨
