### ISSUE TITLE
Upgrading from 2.7.1 to 3.0.1 solved

### ISSUE THREAD

**Issue by pbstudent** [BCcampus/pressbooks-textbook#85]
Existing sites with theme appeared to have CSS broken.

Symptoms:
- textboxes disappeared
- text body width displays narrow on web page

Solution - theme re-activation:

1. Activated Austin Classic
2. Re-activated Pressbooks Textbook

Now displays correctly.

Alternative solution?

**Comment by bdolor** [comment]
This function https://github.com/BCcampus/pressbooks-textbook/blob/dev/pressbooks-textbook.php#L414 triggers a recompile of sass to css required for a switch to sassified theme. It triggers on a per book basis when a theme version updated is detected. Would like to confirm/rule out that the issue you are experiencing is not related to either your browser cache or mod_expires on your server. Have you tried clearing browser cache to achieve the same effect?

**Comment by pbstudent** [comment]
I tested clearing cache with a different browser (Safari instead of Firefox) on the dev site with the same results.  Clearing browser cache did not change presentation.  Only when I followed the above solution did the theme reset. It worked!
ps. now if I can figure out how to get the number list alignment fixed...

**Comment by bdolor** [comment]
I can't reproduce the behaviour reported here.
