### ISSUE TITLE
List alignment

### ISSUE THREAD

**Issue by pbstudent** [BCcampus/pressbooks-textbook#86]
Configuration: PB 3.9.7.1 and PBT 3.0.1

Bullet list alignment displays correctly with hanging indent.
Numbered lists display incorrectly with text aligned to number rather than hanging indent, as per illustration:
![3 design mem](https://cloud.githubusercontent.com/assets/24277755/22462540/fe886428-e7ad-11e6-819c-ce2e2f79d265.png)

**Comment by pbstudent** [comment]
Could it be a CSS fix? I found the following idea (http://stackoverflow.com/questions/10428720/how-to-keep-indent-for-second-line-in-ordered-lists-via-css) but not sure if this solves the issue without breaking something else:

ol {
margin-left: 0;
padding-left: 3em;
list-style-position: outside;
}

**Comment by pbstudent** [comment]
PBT 3.0.2.1

No change in numbered list alignment of text over flow:

[updraftplus.2.12.40.zip](https://github.com/BCcampus/pressbooks-textbook/files/915896/updraftplus.2.12.40.zip)


Is this a PB issue or a PBT issue?

**Comment by pbstudent** [comment]
PBT 3.0.2.1

No change in numbered list alignment of text over flow:
![3 design mem pbt 3 0 2 1](https://cloud.githubusercontent.com/assets/24277755/24948892/19a9ce68-1f6c-11e7-94dc-a6800b76c6aa.png)

Is this a PBT or PB issue?

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-textbook/commit/dffaff0ce9456a49940613e0f053eafe606a82f9
