### ISSUE TITLE
ODT export not visible to public

### ISSUE THREAD

**Issue by pbstudent** [BCcampus/pressbooks-textbook#87]
ODT export download file was visible on frontpage in previous version of PBT 2.7x but not in the current release 3.0.1

Any quick fix possible?

Thanks,

Upon further examination of the book site homepage, there is white space with an active link but no icon visible, suggesting that an icon link is missing...?
*noteworthy that clicking on link produces a File not found error.

**Comment by bdolor** [comment]
ODT export dependencies have changed and is not something that is controlled by PBT. 

https://github.com/pressbooks/pressbooks/blob/dev/readme.txt#L321
