### ISSUE TITLE
Navigation Left Right Arrows in body of text

### ISSUE THREAD

**Issue by pbstudent** [BCcampus/pressbooks-textbook#93]
PBT 3.0.2.1

I reinstalled PBT plugin but no change:

![3 design mem pbt 3 0 2 1](https://cloud.githubusercontent.com/assets/24277755/24949742/009b4dc2-1f6f-11e7-8635-aa89ef1f1975.png)

**Comment by pbstudent** [comment]
Noteworthy Pattern

The above theme presentation only occurs on every second book in PB.  Therefore, the 1st, 3rd, 5th etc. are not affected, as I was able to change themes, refresh browser on new theme, and reactivate Open Textbook theme, refresh browser, and all was correct in display.

**Comment by bdolor** [comment]
I can't recreate the issue reported here.

**Comment by pbstudent** [comment]
I was able to fix the issue on one updated PB instance by activating a different theme then reactivating Open Textbook 1.0 theme.  In that instance PB was was installed within WP plugin install.  In another PB instance changing themes did not change the Book site theme (stuck in original theme) - in this situation I had installed the instance via FTP.  I will try to uninstall PB and reinstall via WP to see if this fixes the themes issue.

**Comment by pbstudent** [comment]
I reinstalled PB from the WP upload plugin page.  The issue remains the same. A key observation is that I am unable to change the theme from Open Textbook to something else.  Therefore next test is to uninstall OT and see if I can force book to a new theme without OT, then reinstall OT / PBT.

**Comment by pbstudent** [comment]
Quickfix - I deleted the offending style.css in /wp-content/uploads/sites/1/css/
Activated another theme on above site, then reactivated OT theme. Now everything displays correctly.
One caveate: the new style.css has the auto-permissions set to 644 (I do not know if this will be a future problem ?)

**Comment by pbstudent** [comment]
Issue - somehow style.css were not all with updated when the WP PB were updated.
