### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by rwestmacott** [BCcampus/pressbooks-textbook#96]
After upgrading the pressbooks-textbook plugin to version 3.0.2.1 the following behaviour occurred:

- The first time only visiting a book site results in an internal Server 500 error.
- Any subsequent loads of that site work correctly as expected.

Reviewing the wordpress debug log displayed this error:

PHP Fatal error:  Call to undefined method Pressbooks\GlobalTypography::updateWebBookStyleSheet() in /var/www/webapps/pressbooks/wp-content/plugins/pressbooks-textbook/pressbooks-textbook.php on line 429

Looking at line 429, this appears to be a problem recompiling the sass files into the styles.css file, at least first time per site .

Pressbooks plugin version installed is: 3.9.8.2
pressbooks-mpdf plugin version installed is: 1.6.2.3

**Comment by bdolor** [comment]
Thanks for reporting @rwestmacott - I will look into this

**Comment by bdolor** [comment]
fixed via https://github.com/BCcampus/pressbooks-textbook/commit/c6fb0429f7a99a800705053c2283a4adb955af72 related to https://github.com/pressbooks/pressbooks/pull/710/files

will release a new version with this change soon.
